### ISSUE TITLE
Kemini: Transmit does not finalize experiment

### ISSUE THREAD

**Issue by N3h3miah** [N3h3miah/OrbitalMaterialScience#101]
After "Transmit", experiment status seems to be "finished"; it's possible to
"Finalize" again, and return experiment to Kerbin for more science.
Also possibly to "Clean" experiment (if Lab is present) but has no effect.
- [x] check for other experiments

**Comment by mwerle** [comment]
Not fixed; after "Transmit" state is set to "Finished"; can still finalize again.

**Comment by mwerle** [comment]
Confirmed fixed.
