### ISSUE TITLE
Show name or description in add experiment

### ISSUE THREAD

**Issue by N3h3miah** [N3h3miah/OrbitalMaterialScience#104]
Descriptions - experiment information and names are only available in R&D
center.  Too many abbreviated experiments; very difficult to keep track.

Maybe tool-tip with requirements on button hover

**Comment by N3h3miah** [comment]
@mwerle How is this?

**Comment by mwerle** [comment]
That's great - better than tooltip.
Would be good to have the same info in-flight too.

**Comment by N3h3miah** [comment]
I try to find a way to include this information maybe even the current state for multistep experiments. #114
