### ISSUE TITLE
[Enhancement] Add Experiment - should show name + required equipment/lab

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#109]
When adding experiments to an ESC, only the experiment abbreviation is shown.
It would be great to (tooltip?) show the full name, description, and the required equipment.

**Comment by N3h3miah** [comment]
This should be the case since a2bde5ae09fc8d69ace8115a8493395019d0745e as part of #104

**Comment by mwerle** [comment]
You're updating faster than I can test! :) Merging now..
Are you on IRC at all? Might be useful to discuss in real time..

**Comment by mwerle** [comment]
Duplicate of #104

**Comment by N3h3miah** [comment]
I'm on skype and google hangout.
