### ISSUE TITLE
OMS ES3 Capsule marked as debris

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#111]
The OMS ESC2 Capsule is always marked as debris rather than probe.

**Comment by N3h3miah** [comment]
I have a look at the internal batteries may adapt them. It is difficult to integrate RCS because you don't know where the center of mass of the final craft would be. For an other version I maybe can come up with something.

**Comment by N3h3miah** [comment]
I always hit the wrong button.

**Comment by mwerle** [comment]
I wasn't necessarily meaning to add additional resources to this pod; it might make it overpowered if you do.  Just noting that it may be difficult to balance this part.

**Comment by N3h3miah** [comment]
Based the new values closer to the command pod mk2 and added Mono Propellant. It is actually sort of a cargo version of the mk2 so I think it makes sense.
