### ISSUE TITLE
KEES Carrier becomes debris while attached to vessel

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#115]
Mods (apart from OMS):
* KAS, US, KER

Steps:
1. Attached KEES carrier to a vessel, added an experiment, and started it. 
2. Switched to another vessel.
3. Switched to KSC, then Tracking Station
4. In Tracking Station, KEES carrier is now listed as a separate Debris vessel.
5. On switch to KEES Carrier, KSP locked up (constant Null-Reference exceptions in log)
(restart KSP)
6. On switch to parent vessel, KSP slow, but running (constant NULL-Reference exceptions in log). KEES Carrier appears to be attached to vessel and functioning as expected.

![persistent sfs bak_nullref_keescarrier](https://cloud.githubusercontent.com/assets/615724/6320286/54e65084-bad1-11e4-98ac-1a385ecb25b8.png)

These exceptions after switching to KEES Carrier:
````
[FLIGHT GLOBALS]: Switching To Vessel KEES Passive Experiment Carrier ---------------------- 
...
NullReferenceException: Object reference not set to an instance of an object
  at Vessel.recurseCoMs (.Part part) [0x00000] in <filename unknown>:0 
  at Vessel.findLocalCenterOfMass () [0x00000] in <filename unknown>:0 
  at FlightCamera.LateUpdate () [0x00000] in <filename unknown>:0 
....
NullReferenceException: Object reference not set to an instance of an object
  at Vessel.recurseCoMs (.Part part) [0x00000] in <filename unknown>:0 
  at Vessel.findWorldCenterOfMass () [0x00000] in <filename unknown>:0 
  at Vessel.FixedUpdate () [0x00000] in <filename unknown>:0 
````
These (and more) exceptions after switching to parent ship:
````
NullReferenceException: Object reference not set to an instance of an object
  at Vessel.recurseCoMs (.Part part) [0x00000] in <filename unknown>:0 
  at Vessel.findWorldCenterOfMass () [0x00000] in <filename unknown>:0 
  at Vessel.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: 4294967295)

NullReferenceException: Object reference not set to an instance of an object
  at Vessel.recurseCoMs (.Part part) [0x00000] in <filename unknown>:0 
  at Vessel.findWorldCenterOfMass () [0x00000] in <filename unknown>:0 
  at Vessel.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: 4294967295)

KEES Passive Experiment Carrier Unloaded
````

**Comment by mwerle** [comment]
NB: Carrier only remains debris while in space.  If landed, the game removes the debris when the context is switched away from the vessel.

**Comment by mwerle** [comment]
Ok, another update - while my patch fixes the issue of the PEC becoming debris when taken out of a container and being attached to a vessel, there's another issue:  on accelerating, when the PEC is decoupled due to excessive G-Forces, it also causes a phantom piece of debris to spawn.  Methinks the entire decouple() call is fraught with danger.

**Comment by N3h3miah** [comment]
Found it! decouple was called twice in 2 consecutive frames causing the copy.

**Comment by mwerle** [comment]
W00t!  I spent a fair bit of time on this..  couldn't figure out what was wrong since the KAS code does pretty much the same thing.  Glad you tracked it down!

**Comment by mwerle** [comment]
*SIGH*
Not fixed.

I have no idea why my fix above seemed to work (and it definitely did!) and yet the current code fails again.  The dump below clearly shows that when the max-G is triggered during the KAS routine, the part is it's own vessel.  So I guess we need to add another check: part.parent != null.

```
[LOG 23:14:09.902] 2/25/2015 11:14:09 PM,KerbalAlarmClock,Vessel Change from 'Kemini - KEES' to 'Bob Kerman'
[ERR 23:14:17.803] Input is null

[LOG 23:14:17.825] stage manager starting...
[LOG 23:14:17.825] stage manager resuming...
[LOG 23:14:17.826] stage count is: 0
[LOG 23:14:17.827] [KAS] WaitAndGrab(Container) - Waiting rigidbody to initialize...
[LOG 23:14:17.925] [KAS] WaitAndGrab(Container) - Waiting rigidbody to initialize...
[LOG 23:14:17.930] [KAS] WaitAndGrab(Container) - Waiting rigidbody to initialize...
[LOG 23:14:18.007] [KAS] WaitAndGrab(Container) - Rigidbody initialized, setting velocity...
[LOG 23:14:18.007] [KAS] WaitAndGrab(Container) - Waiting velocity to apply by waiting 0.1 seconds...
[LOG 23:14:18.130] [NE] KEES PEC over max G, decouple
NE.KEES.PEC (NE_Science.KEES_PEC)
	node:               AttachNode
	exp:                
	decoupled:          False
	part:               NE.KEES.PEC (Part)
	part.parent:        
	vessel:             NE.KEES.PEC (Vessel)
	vessel.isEva:       False
	vessel.geeForce:    456.628743142491
	maxGforce:          2.5

[LOG 23:14:18.236] [KAS] WaitAndGrab(Container) - Grab part...
[LOG 23:14:18.256] [KAS] Grab - Grabbing part :NE.KEES.PEC
[LOG 23:14:18.277] [KAS] WaitAndGrab(Container) - End of coroutine...
[WRN 23:14:18.350] [PartJoint]: None of the provided nodes was valid!
[LOG 23:14:23.406] [NE] NE.KEES.PEC (NE_Science.KEES_PEC)
	node:               AttachNode
	exp:                
	decoupled:          True
	part:               NE.KEES.PEC (Part)
	part.parent:        kerbalEVA (Bob Kerman) (Part)
	vessel:             kerbalEVA (Bob Kerman) (Vessel)
	vessel.isEva:       True
	vessel.geeForce:    0.000102362949139531
	maxGforce:          2.5

[LOG 23:14:24.737] [KAS] StartPointer(pointer)
[LOG 23:14:26.379] [KAS] Attachment started...
[LOG 23:14:26.381] [KAS] Drop - Dropping part :NE.KEES.PEC
[LOG 23:14:26.457] [KAS] UpdatePointer(Pointer) Attach with couple or static method
[LOG 23:14:32.393] [00:00:14]: Bob Kerman boarded Command Pod Mk1 on Kemini - KEES.
[LOG 23:14:32.394] [FLIGHT GLOBALS]: Switching To Vessel Kemini - KEES ---------------------- 
```

**Comment by mwerle** [comment]
Tried my additional fix; (appears to) work, will send a pull request shortly.

Further issues:

1)  the experiment keeps running after the PEC decouples from the vessel. 
Even while the Kerbal EVA's, retrieves it, stores it in a container, then adds it to a PEC again.

2) the "decoupled" flag remains set to "true". So after EVA and re-attach to vessel, the PEC will never again break off.
```
[NE] NE.KEES.PEC (NE_Science.KEES_PEC)
        node:               AttachNode
        exp:                NE.KEES.ODC (NE_Science.KEESExperiment)
        decoupled:          True
        part:               NE.KEES.PEC (Part)
        part.parent:        NE.KEES.PC (Part)
        vessel:             mk1pod (Kemini - KEES) (Vessel)
        vessel.isEva:       False
        vessel.geeForce:    5.38810255597887
        maxGforce:          2.5
```

**Comment by mwerle** [comment]
Current trunk seems to work!
You're going to hate me... but I only just thought of this.  Would it make more sense for an experiment to be "ruined" instead if there's an unplanned detachment?
