### ISSUE TITLE
Create Company and Flag

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#116]
Would be nice to have a Nehemiah company with flag in-game for missions.

**Comment by N3h3miah** [comment]
I'd love to have this, all we need is an artistic person that creates a flag.

**Comment by mwerle** [comment]
Heh, don't look at me!!  But maybe try here?
http://forum.kerbalspaceprogram.com/threads/30753-Request-a-flag%21?highlight=flag+request

**Comment by N3h3miah** [comment]
I added my draft and changed the contracts to use Nehemiah Engineering as agent
