### ISSUE TITLE
KEES Experiment becomes undocked when switching vessels

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#119]
When switching to a vessel with a running KEES Experiment the Experiment warns that it has become undocked (even though it hasn't) and stops.

Private variable "docked" is not persisted and defaults to "false".  updateState() calls checkUndocked() when experiment is in "running" state, triggering the warning and the experiment resetting itself.  It can then be restarted as normal.

**Comment by N3h3miah** [comment]
fixed 522fd7ba508b489e7d82b8f734cee4214e4060ec
