### ISSUE TITLE
NullReferenceException in getAllLabCrewMembers()

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#124]
I got a weird issue on my test orbital station when installing an USU into an MPL-600, followed by installing the SpiU experiment - a Null Reference Exception raised in getAllLabCrewMembers().  Following on from this the state of the MPL-600 seemed partially corrupted; removing all crew members did not show the lab as understaffed, and removing and reinstalling various experiments showed strange state ("USU: ADUM installed" as well as "Move SpiU").
I reproduced the issue in the same game session using a small testbed vessel on the launchpad.
Unfortunately I did not capture either the exception, nor a screenshot.

After modifying code and restarting KSP I was unable to reproduce; both testbed on launchpad and orbital station behaved as expected.

**Comment by N3h3miah** [comment]
No clue what happened to cause this. Your fix should help to prevent spreading of the NRE.

**Comment by mwerle** [comment]
First off, congrats on releasing the mods!! Looking forward to playing 
with them "properly" now (although I'll still keep an eye out for 
issues, of course..)

Just saw this in the KLS thread:
> The experiments are based on real life ISS experiments. The Experiments 
> need to test several Kerbals to complete.
> Advanced Diagnostic Ultrasound in Microgravity (ADUM) Kerbals needed: 4 
> Real Life Experiment
> Sonographic Astronaut Vertebral Examination (SpiU) Kerbals needed: 6 
> Real Life Experiment

and that would explain why I couldn't complete the experiments last 
night.. was too tired to keep testing so I was going to pick that up 
again tonight, didn't realise you were releasing today :)


Anyway, maybe I missed it, but I think there should be some in-game 
indicator of how many kerbals each experiment requires (and how many 
have already been testeed) in some sort of status display.

Cheers,
  - Micha.

**Comment by N3h3miah** [comment]
There is a list of the already tested Kerbals. The list to choose the next test subject shows the already tested Kerbals. If all the Kerbal in the lab are already tested only those are shown. But I should show the number of needed Kerbals too.

**Comment by mwerle** [comment]
On 4 March 2015 18:16:32 GMT+00:00, N3h3miah <notifications@github.com> wrote:
>There is a list of the already tested Kerbals. The list to choose the
>next test subject shows the already tested Kerbals. If all the Kerbal
>in the lab are already tested only those are shown. But I should show
>the number of needed Kerbals too.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/N3h3miah/OrbitalMaterialScience/issues/124#issuecomment-77213551

Yeah, saw the available and tested kerbals but had no idea had to test more to complete the experiment.  
-- 
The glass is twice as big as it needs to be.
