### ISSUE TITLE
Causing sticky docking ports and grabbers in 64-bit

### ISSUE THREAD

**Issue by calculon000** [N3h3miah/OrbitalMaterialScience#6]
I'm not sure why, but in my 64-bit 0.24.2 KSP, which is loaded with a bunch of other mods, I was having an issue where releasing/undocking the advanced Grabber unit and occasionally a docking port would result in nothing happening, and the option to release/undock would be gone from the right-click menu as if it was worked. The result being that the dock/grabber unit was forever attached, without giving me the ability to ever separate them again.

I uninstalled by deleting the NehemiahInc folder from my gamedata directory, and the problem was instantly fixed. Luckily was was able to revert to a state where my space station I was working on did not yet include any parts from this mod.

This COULD be an interaction with a second mod, I'm not sure, but I do know that the issue is not present with the OrbitalMaterialScience mod uninstalled.

**Comment by N3h3miah** [comment]
Did you use Kerbal Joint Reinforcement at the same time?

**Comment by Volkkeslate** [comment]
While this is an old bug i'd just like to point out that this is a common bug with 64 bit KSP builds and its general conflict with any mods at all. You'd be hard pressed to be able to fix the issue since it's not a mod side issue so much as it's a client side issue.

**Comment by calculon000** [comment]
Yeah it hasn't shown up since I switched back to 32-bit KSP.

Thanks!
