### ISSUE TITLE
Add Experiment dialog breaks if trying to add multiple experiments without pressing close

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#70]
OMS v0.6a1
Verified under Linux (x64) & Windows (x32).

Trying to add multiple experiments to OMS ESC2 or ESC4 in the VAB without pressing the "close" button in-between can cause the UI to become confused.
It may not react to mouse-clicks properly (adding the wrong experiment), or at all (buttons become unresponsive).  Sometimes it's possible to recover, other times must exit VAB.
Causes other dialogs (including system ones; eg name of craft) to become unresponsive.

SUGGEST: Selecting an experiment automatically closes the selection dialog, rather than requiring selection + pressing close.
SUGGEST2: Modify right-click menu on Experiment Storage Container to have status and add button on same line for each slot.  It's slightly confusing to not have them next to each other.

**Comment by N3h3miah** [comment]
Selecting should close the window. It does for me.

**Comment by mwerle** [comment]
Just re-tested on a fresh install on a different PC and selecting also closes for me.
Will try to repro.

**Comment by N3h3miah** [comment]
I guess I can get rid of the status in the VAB because for each slot there is always an action showing. And when I replace "experiment" with the abbreviation of the experiment in the remove action the actual content if the container is visible.

**Comment by N3h3miah** [comment]
Fixed the window issue, I leave it open so @mwerle  can verify the selection closing isssue

**Comment by mwerle** [comment]
Compiled latest trunk and works as intended for me now.
Original issue -may- have been due to an older test-save I was using - discovered I had similar problems with latest build until I started a brand new save.
New interface is IMHO better - thanks!

**Comment by mwerle** [comment]
Actually, I think I -finally- tracked down the root of the issue; alternatively it's a related issue.  Your code fires off a onVesselWasModified event in ExperimentStorage.showAddGui() even if part.vessel is null.  This causes a NullReference exception to be thrown by ConnectedLivingSpace (which I sometimes load into my game for testing the CLS configs I'm tweaking), which in turn prevents the experiment from being loaded into the experiment container.

The EquipmentRackContainer class does not fire off the same event and hence worked fine.

```
diff --git a/Plugin/NE Science/ExperimentStorage.cs b/Plugin/NE Science/ExperimentStorage.cs
index 4fd86b7..3a96c60 100644
--- a/Plugin/NE Science/ExperimentStorage.cs    
+++ b/Plugin/NE Science/ExperimentStorage.cs    
@@ -334,7 +334,11 @@ namespace NE_Science
                     NE_Helper.log(e.getNode().ToString());
                     part.mass += e.getMass();
                     NE_Helper.log("new mass: " + part.mass + "; fireEvent");
-                    GameEvents.onVesselWasModified.Fire(part.vessel);
+                                       if (null == part.vessel) {
+                                               NE_Helper.log("part.vessel is null!");
+                                       } else {
+                                               GameEvents.onVesselWasModified.Fire (part.vessel);
+                                       }
                     Events["chooseEquipment"].guiName = "Remove " + e.getAbbreviation();
                     showGui = 0;
                 }
```

Log:
[NE] new mass: 0.5; fireEvent
 
(Filename: /BuildAgent/work/d63dfc6385190b60/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

[NE] part.vessel is null!

**Comment by mwerle** [comment]
So not sure if CLS should be checking for NULL in OnVesselWasModified(), or whether you're breaking the contract of the event by passing in NULL.  Haven't tried with other mods to see if they break as well or whether they check for NULL.
The core game seems to deal with it fine, assuming it handles OnVesselWasModified() somewhere.

**Comment by N3h3miah** [comment]
Thanks for hunting this one down.
