### ISSUE TITLE
KEES experiments can be cleaned, but not reused

### ISSUE THREAD

**Issue by mwerle** [N3h3miah/OrbitalMaterialScience#76]
Expected Result:
Experiment can be cleaned and reused
OR
Experiment can not be cleaned

Actual Result:
Experiment can be cleaned, but not reused

Steps to reproduce:
Take KEES experiment out of container; Store on carrier, run experiment, finalize experiment, transmit results. Can now use Mobile Processing Lab (stock) to clean the experiment, but experiment remains in finalized state and cannot be reused even if taken from carrier, stored in container, retrieved from container, and placed back on carrier.

**Comment by mwerle** [comment]
I've got a patch which fixes this, but there seem to be quite a few inconsistencies with the way KEES experiments work.  Run out of time testing for now though.

**Comment by N3h3miah** [comment]
Actually the experiment can not be cleaned and reused. But my short search did not come up with the right setting to prevent cleaning by the Lab. You do a really good job in tracking down bugs.
