### ISSUE TITLE
Tech Tree with Kemini

### ISSUE THREAD

**Issue by N3h3miah** [N3h3miah/OrbitalMaterialScience#86]
Review the Tech Tree with the Kemini experiments.

* Where to put the Kemini experiments
* Move other experiments or parts

Debends on: #83 
Part of : #85

**Comment by Volkkeslate** [comment]
I like the current tech tree positioning for the new Kemini experiments, so leaving them in basic rocketry and survivability seems like a good location for the time being.

For the KEES experiments i think moving them a node further down the tree would balance things out; So moving the experiment carrier, container, POSA I, and the micrometeroid and debris experiments to "Science Tech" and then moving the experiments that are currently located in "Science Tech" (OBC and POSA II) to the "Space Exploration" node. Relocating these also places them to be unlocked at the same time as the first batteries and solves the electric charge issue that we previously had.

I'm unsure as to where to move the other parts like the labs and such, i suppose it would depend on if you want these parts to fill the mid game science area or be more oriented towards later game.

**Comment by N3h3miah** [comment]
I moved the OMS und KR(Kerbal Research) up and assigned the new. The 2 early science programs Kemini and KEES allow this.
